# Generated by Django 5.0.1 on 2024-03-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='Product_Detail',
        ),
    ]
